# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oathkeeper-maester

before:
  hooks:
    - "go mod download"

builds:
  - flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm64
    goos:
      - linux
      - darwin

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-amd64"
      - "oryd/oathkeeper-maester:{{ .ShortCommit }}-amd64"
      - "oryd/oathkeeper-maester:latest"
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-arm64"
      - "oryd/oathkeeper-maester:{{ .ShortCommit }}-arm64"
      - "oryd/oathkeeper-maester:latest"
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"

release:
  prerelease: auto
  name_template: "{{ .Tag }}"
