# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oathkeeper-maester
version: 2
before:
  hooks:
    - "go mod download"

builds:
  - id: linux-amd64
    flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - linux
  - id: linux-arm64
    flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
    goos:
      - linux
  - id: linux-i386
    flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - 386
    goos:
      - linux
  - id: darwin-amd64
    flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
    goos:
      - darwin
  - id: darwin-arm64
    flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - arm64
    goos:
      - darwin

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-amd64"
      - "oryd/oathkeeper-maester:{{ .ShortCommit }}-amd64"
      - "oryd/oathkeeper-maester:latest"
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
    dockerfile: ".docker/Dockerfile-release"
    ids:
      - "linux-amd64"
  - image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-arm64"
      - "oryd/oathkeeper-maester:{{ .ShortCommit }}-arm64"
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
    dockerfile: ".docker/Dockerfile-release"
    ids:
      - "linux-arm64"

docker_manifests:
  - name_template: "oryd/oathkeeper-maester:{{ .Tag }}"
    id: "tag"
    image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-amd64"
      - "oryd/oathkeeper-maester:{{ .Tag }}-arm64"
  - name_template: "oryd/oathkeeper-maester:latests"
    id: "latests"
    image_templates:
      - "oryd/oathkeeper-maester:{{ .Tag }}-amd64"
      - "oryd/oathkeeper-maester:{{ .Tag }}-arm64"

release:
  prerelease: auto
  name_template: "{{ .Tag }}"
