# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oathkeeper-maester

env:
  - GO111MODULE=on

before:
  hooks:
    - "go mod download"

builds:
  - flags:
      - -a
    binary: manager
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - 386
      - arm64
    goos:
      - linux
      - darwin

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc

dockers:
  - image_templates:
      - "oryd/oathkeeper-maester:v{{ .Major }}"
      - "oryd/oathkeeper-maester:v{{ .Major }}.{{ .Minor }}"
      - "oryd/oathkeeper-maester:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
      - "oryd/oathkeeper-maester:{{ .Env.DOCKER_SHORT_TAG }}"
      - "oryd/oathkeeper-maester:latest"

release:
  prerelease: auto
  name_template: "{{.Env.RELEASE_NAME}}"
