# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: oathkeeper-k8s-controller

env:
 - GO111MODULE=on

before:
 hooks:
  - "go mod download"
  - "go install github.com/gobuffalo/packr/v2/packr2"
  - packr2

builds:
 - flags:
    - -a

   binary: oathkeeper
   env:
    - CGO_ENABLED=0
   goarch:
    - amd64
    - 386
    - arm
    - arm64
   goarm:
    - 5
    - 6
    - 7
   goos:
    - freebsd
    - linux
    - windows
    - darwin

archives:
 - replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: 32-bit
    amd64: 64-bit
   format_overrides:
    - goos: windows
      format: zip

snapshot:
 name_template: "{{ .Tag }}-next"

changelog:
 sort: asc

brew:
 github:
  owner: ory
  name: homebrew-oathkeeper-k8s-controller
 homepage:  https://www.ory.sh
 commit_author:
  name: ory
  email: hi@ory.sh

scoop:
 bucket:
  owner: ory
  name: homebrew-oathkeeper-k8s-controller
 homepage:  https://www.ory.sh
 commit_author:
  name: ory
  email: hi@ory.sh

dockers:
 - image_templates:
    - "oryd/oathkeeper-k8s-controller:v{{ .Major }}"
    - "oryd/oathkeeper-k8s-controller:v{{ .Major }}.{{ .Minor }}"
    - "oryd/oathkeeper-k8s-controller:v{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    - "oryd/oathkeeper-k8s-controller:{{ .Env.DOCKER_SHORT_TAG }}"
    - "oryd/oathkeeper-k8s-controller:latest"

release:
 prerelease: auto
 name_template: "{{.Env.RELEASE_NAME}}"
