version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ory/oathkeeper-k8s-controller
    steps:
      - run:
          name: Enable go1.12 modules
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV
            source $BASH_ENV
      - checkout
      - run: make test

workflows:
  version: 2
  "test, build":
    jobs:
      - build:
          filters:
            tags:
              only: /.*/


