---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns-1
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-1
  namespace: test-ns-1
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-no-upstream
  namespace: test-ns-1
spec:
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-2
  namespace: test-ns-1
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ns-2
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-1
  namespace: test-ns-2
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-2
  namespace: test-ns-2
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-cm
  namespace: default
spec:
  configMapName: some-cm
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
  - handler: anonymous
  authorizer:
    handler: allow
  mutators:
  - handler: noop
    config: {}
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-handlers-1
  namespace: default
spec:
  configMapName: handlers-test-cm
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
    - handler: anonymous
      config:
        foo: bar
        long: |
            {
              "bar": "foo"
            }
  authorizer:
    handler: allow
    config:
      lorem: ipsum
      answer: 42
  mutators:
    - handler: noop
      config: {}
    - handler: id_token
      config:
        ttl: 3600s
        claims: |
          {
            "aud": [ "hub.animeapis.dev" ],
            "session": {{ .Extra | toJson }}
          }
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-handlers-2
  namespace: default
spec:
  configMapName: handlers-test-cm
  authenticators:
    - handler: anonymous
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
      config:
        ttl: 3600s
        claims: |
          {
            "aud": [ "hub.animeapis.dev" ],
            "session": {{ .Extra | toJson }}
          }
  match:
    url: <{https,http}>://hub.animeshon.dev/<**>
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]