resources:
  - certificate.yaml

# the following config is for teaching kustomize how to do var substitution
vars:
  - fieldref:
      fieldpath: metadata.namespace
    name: NAMESPACE
    objref:
      kind: Service
      name: webhook-service
      version: v1
  - fieldref:
      fieldpath: ""
    name: CERTIFICATENAME
    objref:
      group: certmanager.k8s.io
      kind: Certificate
      name: serving-cert
      version: v1alpha1
  - fieldref:
      fieldpath: metadata.name
    name: SERVICENAME
    objref:
      kind: Service
      name: webhook-service
      version: v1

configurations:
  - kustomizeconfig.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
